### ISSUE TITLE
Use analysis-specific template when displaying slices

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-fslhtml#12]
As discussed in https://github.com/incf-nidash/nidmresults-fslhtml/pull/9#discussion_r155795376, rather than always using the FSL template, we could display the activations onto a template that is in the same world coordinate system as the one used for the original analysis.

In NIDM-Results the world coordinate system of an excursion set is stored in the corresponding [Coordinate Space](http://nidm.nidash.org/specs/nidm-results_130.html#dfn-nidm_0000016) entity in the [nidm:'in World Coordinate System'](http://nidm.nidash.org/specs/nidm-results_130.html#dfn-nidm_0000105) attribute.

**Comment by TomMaullin** [comment]
This issue was solved in PR #23
