### ISSUE TITLE
Use nibabel for operations on images

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-fslhtml#13]
As discussed in [#9 (comment 1)](https://github.com/incf-nidash/nidmresults-fslhtml/pull/9#discussion_r155271620) and [#9 (comment 2)](https://github.com/incf-nidash/nidmresults-fslhtml/pull/9#discussion_r155795376), rather than always relying on FSL commands, we should use nibabel for operations on NIfTI images as this is easier in Python. 

(To generate displays we will still use FSL functions as much as we can so that we can more easily reproduce the FSL output).

**Comment by TomMaullin** [comment]
This issue was solved in PR #23
