### ISSUE TITLE
Missing slice images in FSL

### ISSUE THREAD

**Issue by TomMaullin** [incf-nidash/nidmresults-fslhtml#14]
The viewer currently does not account for the case of FSL generated NIDM-Results packs that are missing slice images.

**Comment by cmaumet** [comment]
Hi @TomMaullin! I thought this was solved by https://github.com/incf-nidash/nidmresults-fslhtml/pull/9? Can you clarify how this issue is different? Thanks!

**Comment by TomMaullin** [comment]
Ah yes sure! Sorry! This is for the use case when a pack has been generated by FSL but did not have a recorded slice image.

Currently the viewer only creates a slice image if it is looking at a SPM-generated nidm-results pack, not in the case it is looking at an FSL-generated nidm-results pack which is missing a slice image. 

This shouldn't be much work to resolve but I created an issue on it as none of the PR's I have done lately were really related enough to add this into.

**Comment by cmaumet** [comment]
I understand! Thanks! Do you actually have examples of FSL packs where the view in slices is missing? If that's the case, then please report them at https://github.com/incf-nidash/nidmresults-fsl.

**Comment by TomMaullin** [comment]
Oh no don't worry! I have no examples of that. I thought I had best account for it as we did the same for MIPs in the SPM viewer. If you think it's unnecessary I'm happy to close this issue.

**Comment by cmaumet** [comment]
I think it's a useful feature! Creating the slice view anytime it is missing will be especially useful when we add more software packages (e.g. AFNI). I am happy to hear that's not happening in our examples though ;)

**Comment by TomMaullin** [comment]
This issue was solved in PR #23
