### ISSUE TITLE
Next features to work on

### ISSUE THREAD

**Issue by nicholst** [incf-nidash/nidmresults-fslhtml#4]
- [x] Generate PNG image of significant blobs when absent, using FSL
- [x] Peak table
- [x] Further testing of all NIDM outputs... conjunctions, contrast masking...

**Comment by TomMaullin** [comment]
The PNG image of significant blobs issue has now been resolved in #9

**Comment by cmaumet** [comment]
@TomMaullin: thanks! Can you tick the items in Tom N.'s list as you complete them? This will update the summary (currently  "0 of 3") displayed when listing all issues at: https://github.com/incf-nidash/nidmresults-fslhtml/issues.

**Comment by TomMaullin** [comment]
Hi @cmaumet ,

Yes I will do this as they are removed!

**Comment by TomMaullin** [comment]
The final part of this issue (testing) was resolved in PR #22
