### ISSUE TITLE
Post-stats for conjunction inference

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-fslhtml#5]
So far the conjunction inference is not handle in the post-stats page.

**Comment by TomMaullin** [comment]
What would be the ideal output for the conjunction inference on the post-stats page. Should the text about thresholding be changed to instead describe the conjunction?

**Comment by cmaumet** [comment]
I think the text describing the thresholding could be kept as it is. But under 'Thresholded activation images' instead of having just "'zstat1'" we could have 
"conjunction: 'zstat1', 'zstat2'". If there are multiple excursion sets, we could have 'zstat1', 'zstat2' (as before) and then the conjunction. Does this help?

**Comment by TomMaullin** [comment]
I see - currently this is dealt with for NIDM-Results conjunction inference packs containing one excursion set but not in the case of multiple.

**Comment by cmaumet** [comment]
That's fine, then only the conjunction will be displayed.

**Comment by TomMaullin** [comment]
Is this sufficient to close this issue? I'm happy to make a separate small branch later to display the multiple excursion sets for conjunction if needed?

**Comment by cmaumet** [comment]
If our example of conjunction can correctly be displayed then I am happy for you to close this issue. If so, can you add a comment mentioning where display of conjunctions was implemented?

**Comment by TomMaullin** [comment]
Ah okay, yes conjunction NIDM-Packs are handled by the if statement on line 550 of the viewer.py function. This can be found here:

https://github.com/incf-nidash/nidmresults-fslhtml/blob/master/nidmviewerfsl/viewer.py#L550
