### ISSUE TITLE
Embed png images in HTML

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-fslhtml#8]
Similarly to what has been done for the SPM viewer (cf. https://github.com/incf-nidash/nidmresults-spmhtml/issues/6), it would be great to embed the png images directly into the html files. 

cf. http://www.techerator.com/2011/12/how-to-embed-images-directly-into-your-html/ for an example.

**Comment by TomMaullin** [comment]
This has now been resolved in PR's #9 and #10 for slice images and background images respectively.
